version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.apis:google-api-services-gmail
    versions:
    - v1-rev20200919-1.31.0
    - v1-rev20210111-1.31.0
  - dependency-name: org.json:json
    versions:
    - "20201115"
